=== prog-nov/fps-iso-20022/eclipse-workspace/ffpdemo/src/com/forms/beneform4j/excel/exception/beneform4j-exception.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="http://www.formssi.com/schema/beneform4j/exception"
	targetNamespace="http://www.formssi.com/schema/beneform4j/exception"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified" version="1.0">
	
	<xsd:element name="exception-config">
		<xsd:annotation><xsd:documentation><![CDATA[
			定义异常配置元素
		]]></xsd:documentation></xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="exception" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
   	
   	<xsd:element name="exception">
   		<xsd:annotation><xsd:documentation><![CDATA[
			定义异常元素
		]]></xsd:documentation></xsd:annotation>
   		<xsd:complexType>
   			<xsd:sequence>
   				<xsd:element ref="exception" minOccurs="0" maxOccurs="unbounded"/>
   			</xsd:sequence>
        	<xsd:attribute name="code" use="required">
        		<xsd:annotation><xsd:documentation><![CDATA[
					异常代码，需要全局唯一，八位字符，前两位大写英文字母，表示异常分类（其中BF为平台保留分类，应用不能使用），后6位为字母数字组合
				]]></xsd:documentation></xsd:annotation>
            	<xsd:simpleType>
            		<xsd:restriction base="xsd:NMTOKEN">
            			<xsd:pattern value="[A-Z]{2}[0-9A-Za-z]{6}"/>
            		</xsd:restriction>
            	</xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="messageKey" type="xsd:string" use="optional">
            	<xsd:annotation><xsd:documentation><![CDATA[
					国际化信息文件中的key值
				]]></xsd:documentation></xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="level" use="optional">
            	<xsd:annotation><xsd:documentation><![CDATA[
					定义异常级别数据类型为枚举类型（INFO、ERROR、FATAL）
				]]></xsd:documentation></xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:NMTOKEN">
			   			<xsd:enumeration value="INFO">
			   				<xsd:annotation><xsd:documentation><![CDATA[
								业务异常，只需要将异常信息提示给业务人员即可，一般由数据校验组件或者开发人员抛出
							]]></xsd:documentation></xsd:annotation>
			   			</xsd:enumeration>
			   			<xsd:enumeration value="ERROR">
			   				<xsd:annotation><xsd:documentation><![CDATA[
								运行时异常，影响本模块，或者局部非重点功能，一般需要技术人员跟踪
							]]></xsd:documentation></xsd:annotation>
			   			</xsd:enumeration>
			   			<xsd:enumeration value="FATAL">
			   				<xsd:annotation><xsd:documentation><![CDATA[
								严重异常，影响整个系统正常运行或者重要模块功能
							]]></xsd:documentation></xsd:annotation>
			   			</xsd:enumeration>
			   		</xsd:restriction>	
				</xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="causes" type="xsd:NMTOKENS" use="optional">
            	<xsd:annotation><xsd:documentation><![CDATA[
					定义异常的可能原因列表，为Throwable类的子类名称，如有多个，使用空格分开
				]]></xsd:documentation></xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="description" type="xsd:string" use="optional">
            	<xsd:annotation><xsd:documentation><![CDATA[
					说明，程序读取配置的时候会忽略该配置
				]]></xsd:documentation></xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
   	</xsd:element>
</xsd:schema>

=== prog-nov/fps-iso-20022/eclipse-workspace/ffp/src/com/forms/beneform4j/core/dao/exception/beneform4j-exception.xml
<?xml version="1.0" encoding="UTF-8"?>
<exception-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.formssi.com/schema/beneform4j/exception"
	xsi:schemaLocation="http://www.formssi.com/schema/beneform4j/exception beneform4j-exception.xsd">
	
	<exception code="BF020000" description="数据访问层异常" messageKey="beneform4j.core.dao" 
		causes="java.sql.SQLException org.apache.ibatis.exceptions.PersistenceException org.springframework.dao.DataAccessException">
		<exception code="BF020001" description="未注册的输出参数" messageKey="beneform4j.core.dao.not_found_ouput_params"/>
		<exception code="BF020002" description="数据库产品名称为空" messageKey="beneform4j.core.dao.database_product_name_is_empty"/>
		<exception code="BF020003" description="未配置数据库方言映射" messageKey="beneform4j.core.dao.not_config_dialect_mapping"/>
		<exception code="BF020004" description="没有找到数据库产品对应的方言" messageKey="beneform4j.core.dao.not_found_dialect"/>
		<exception code="BF020005" description="分页查询时计算总记录条数出现异常" messageKey="beneform4j.core.dao.calculate_totals"/>
		<exception code="BF020006" description="处理存储过程输出参数时出现异常" messageKey="beneform4j.core.dao.handler_output_params"/>
		<exception code="BF020007" description="未找到对应的数据源" messageKey="beneform4j.core.dao.not_found_datasource"/>
		<exception code="BF020008" description="使用OGNL解析需要设置到数据库中的参数时出现异常" messageKey="beneform4j.core.dao.ognl_resolver_db_params"/>
		<exception code="BF020009" description="初始化Mybatis集成数据源时出现异常" messageKey="beneform4j.core.dao.init_mybatis_datasource"/>
		<exception code="BF020010" description="获取数据库元信息异常" messageKey="beneform4j.core.dao.database_meta"/>
		<exception code="BF020011" description="获取表元信息异常" messageKey="beneform4j.core.dao.table_meta"/>
		<exception code="BF020012" description="单次读取数据量超出范围" messageKey="beneform4j.core.dao.fetch_size_out_of_range"/>
		<exception code="BF020013" description="批量执行的参数不正确" messageKey="beneform4j.core.dao.batch_param_is_error"/>
		<exception code="BF020014" description="批量注解@SqlRefs使用不正确" messageKey="beneform4j.core.dao.batch_param_sqlrefs_error"/>
		<exception code="BF020015" description="批量执行参数个数不匹配" messageKey="beneform4j.core.dao.batch_param_size_not_equal"/>
		<exception code="BF020016" description="没有找到sqlId" messageKey="beneform4j.core.dao.not_found_mybatis_sqlId"/>
		<exception code="BF020017" description="一次批量执行必须在同一个数据源" messageKey="beneform4j.core.dao.batch_execute_must_in_some_datasource"/>
		<exception code="BF020018" description="含批量注解，但返回值不是整型数组" messageKey="beneform4j.core.dao.not_match_the_return_type_and_batch_param"/>
		
	</exception>
</exception-config>

=== prog-nov/fps-iso-20022/eclipse-workspace/ffpdemo/src/com/forms/beneform4j/excel/exception/beneform4j-exception.xml
<?xml version="1.0" encoding="UTF-8"?>
<exception-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.formssi.com/schema/beneform4j/exception"
	xsi:schemaLocation="http://www.formssi.com/schema/beneform4j/exception beneform4j-exception.xsd">
	
	<exception code="BF0XLS00" description="Excel组件异常" messageKey="beneform4j.excel">
		<exception code="BF0XLS01" description="读取Excel文件异常" messageKey="beneform4j.excel.read.exception"/>
		<exception code="BF0XLS02" description="写入Excel文件异常" messageKey="beneform4j.excel.write.exception"/>
		<exception code="BF0XLS03" description="Excel列位置错误" messageKey="beneform4j.excel.cell.position"/>
		<exception code="BF0XLS04" description="Excel行位置错误" messageKey="beneform4j.excel.row.position"/>
		<exception code="BF0XLS05" description="Excel校验信息" messageKey="beneform4j.excel.validation.msg"/>
		<exception code="BF0XLS06" description="判断Excel版本信息异常" messageKey="beneform4j.excel.detect.version"/>
		<exception code="BF0XLS07" description="未找到Excel配置模型" messageKey="beneform4j.excel.not_found.em"/>
		<exception code="BF0XLS08" description="不支持的Excel配置模型" messageKey="beneform4j.excel.not_supported.em"/>
		<exception code="BF0XLS09" description="提取Excel数据至JavaBean出现异常" messageKey="beneform4j.excel.extractor.field"/>
		<exception code="BF0XLS10" description="将资源文件应用Freemarker模板异常" messageKey="beneform4j.excel.freemarker.resource"/>
		
		<exception code="BF0XLS11" description="偏移后位置的单元格为空" messageKey="beneform4j.excel.offset.cell.empty"/>
		<exception code="BF0XLS12" description="单元格内容为空" messageKey="beneform4j.excel.cell.emtpy"/>
		<exception code="BF0XLS13" description="只能等于某个值(忽略大小写)" messageKey="beneform4j.excel.cell.only.equal"/>
		<exception code="BF0XLS14" description="只能等于某个值" messageKey="beneform4j.excel.cell.only.equal.case"/>
		<exception code="BF0XLS15" description="不符合格式(忽略大小写)" messageKey="beneform4j.excel.cell.pattern.match"/>
		<exception code="BF0XLS16" description="不符合格式" messageKey="beneform4j.excel.cell.pattern.match.case"/>
		
		<exception code="BF0XLS17" description="Bean模型配置-属性名称不能为空" messageKey="beneform4j.excel.em.xml.loader.property.empty"/>
		<exception code="BF0XLS18" description="Bean模型配置-属性不存在" messageKey="beneform4j.excel.em.xml.loader.property.not.exists"/>
		<exception code="BF0XLS19" description="Bean模型配置-属性类型不匹配" messageKey="beneform4j.excel.em.xml.loader.property.type.error"/>
		<exception code="BF0XLS20" description="Bean模型配置-id和beanType属性不能同时为空" messageKey="beneform4j.excel.em.xml.loader.id.beanType.error"/>
		<exception code="BF0XLS21" description="file-workbook-group元素资源模式为空" messageKey="beneform4j.excel.em.xml.loader.location.patterns.empty"/>
		<exception code="BF0XLS22" description="file-workbook元素资源位置为空" messageKey="beneform4j.excel.em.xml.loader.location.empty"/>
		<exception code="BF0XLS23" description="file-workbook元素资源不存在" messageKey="beneform4j.excel.em.xml.loader.location.not.exists"/>
		<exception code="BF0XLS24" description="text-workbook元素ID为空" messageKey="beneform4j.excel.em.xml.loader.id.empty"/>
		<exception code="BF0XLS25" description="text-workbook元素字符集不支持" messageKey="beneform4j.excel.em.xml.loader.charset.not.support"/>
		<exception code="BF0XLS26" description="没有找到tree-workbook子组件解析器" messageKey="beneform4j.excel.em.xml.loader.not.found.component"/>
		<exception code="BF0XLS27" description="tree-workbook元素无有效的子节点" messageKey="beneform4j.excel.em.xml.loader.tree.workbook.invalid"/>
		
		<exception code="BF0XLS28" description="使用jxls2类库导出Excel异常" messageKey="beneform4j.excel.exports.jxls2"/>
		<exception code="BF0XLS29" description="使用jett类库导出Excel异常" messageKey="beneform4j.excel.exports.jett"/>
		<exception code="BF0XLS30" description="tree-workbook导出时绘制器与组件不匹配" messageKey="beneform4j.excel.exports.component.painter.not.match"/>
		
		<exception code="BF0XLS31" description="批次号格式不符合要求" messageKey="beneform4j.excel.imports.batch.no.pattern"/>
		<exception code="BF0XLS32" description="tree-workbook导入只能含单个grid组件" messageKey="beneform4j.excel.imports.single.grid"/>
		<exception code="BF0XLS33" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS34" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS35" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS36" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS37" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS38" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS39" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS40" description="Excel组件异常" messageKey="beneform4j.excel"/>
		
		<exception code="BF0XLS41" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS42" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS43" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS44" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS45" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS46" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS47" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS48" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS49" description="Excel组件异常" messageKey="beneform4j.excel"/>
		<exception code="BF0XLS50" description="Excel组件异常" messageKey="beneform4j.excel"/>
	</exception>
</exception-config>

=== prog-nov/fps-iso-20022/eclipse-workspace/ffp/src/com/forms/beneform4j/core/util/exception/meta/impl/beneform4j-exception.xml
<?xml version="1.0" encoding="UTF-8"?>
<exception-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.formssi.com/schema/beneform4j/exception"
	xsi:schemaLocation="http://www.formssi.com/schema/beneform4j/exception beneform4j-exception.xsd">
	<!-- 平台异常 -->
	<exception code="BF000000" description="平台异常" messageKey="beneform4j.exception" causes="java.lang.Throwable"/>
	<!-- 平台核心工具层异常，以BF01开始 -->
	<exception code="BF010000" description="平台核心工具层异常" messageKey="beneform4j.core.util">
		<exception code="BF010001" description="出现循环依赖" messageKey="beneform4j.core.util.cycle_dependent"/>
		<exception code="BF010002" description="不支持的字符集" messageKey="beneform4j.core.util.charset_not_supported"/>
		<exception code="BF010003" description="OGNL表达式解析异常" messageKey="beneform4j.core.util.ognl_error"/>
		<exception code="BF010004" description="JDK版本过低" messageKey="beneform4j.core.util.jdk_version_not_supported"/>
		<exception code="BF010005" description="类实例化异常" messageKey="beneform4j.core.util.class_create_error"/>
		<exception code="BF010006" description="访问缓存的权限越界" messageKey="beneform4j.core.util.cache.reject_visit"/>
		<exception code="BF010007" description="未设置默认的缓存名称" messageKey="beneform4j.core.util.cache.unset_default_cache"/>
		<exception code="BF010008" description="未找到默认的缓存名称" messageKey="beneform4j.core.util.cache.not_found_default_cache"/>
		<exception code="BF010009" description="缓存处理出现异常" messageKey="beneform4j.core.util.cache.cache_handler_error"/>
		<exception code="BF010010" description="不支持的Locale对象" messageKey="beneform4j.core.util.locale_not_supported"/>
		<exception code="BF010011" description="SpEL表达式解析异常" messageKey="beneform4j.core.util.spel_error"/>
		
		<exception code="BF010100" description="IO异常" messageKey="beneform4j.core.util.io">
			<exception code="BF010101" description="文件路径不存在" messageKey="beneform4j.core.util.io.file_not_found"/>
			<exception code="BF010102" description="包路径不存在" messageKey="beneform4j.core.util.io.package_not_found"/>
			<exception code="BF010103" description="扫描包路径时出现异常" messageKey="beneform4j.core.util.io.scan_error"/>
		</exception>
		<exception code="BF010200" description="初始化异常" messageKey="beneform4j.core.util.init">
			<exception code="BF010201" description="初始化方法执行异常" messageKey="beneform4j.core.util.init.initmethod_execute_exception"/>
			<exception code="BF010202" description="销毁方法执行异常" messageKey="beneform4j.core.util.init.destorymethod_execute_exception"/>
		</exception>
		
		<exception code="BF010300" description="树异常">
			<exception code="BF010301" description="树构建异常" messageKey="beneform4j.core.util.tree.build_exception"/>
			<exception code="BF010302" description="不能获取节点类型" messageKey="beneform4j.core.util.tree.node_class_is_unknown"/>
			<exception code="BF010303" description="根节点创建异常" messageKey="beneform4j.core.util.tree.root_node_build_exception"/>
			<exception code="BF010304" description="节点关系存在循环" messageKey="beneform4j.core.util.tree.exist_isolate_nodes"/>
			<exception code="BF010305" description="存在空节点，或节点代码为空" messageKey="beneform4j.core.util.tree.exist_empty_node"/>
			<exception code="BF010306" description="节点集为空" messageKey="beneform4j.core.util.tree.nodes_is_empty"/>
			<exception code="BF010307" description="存在重复的节点代码" messageKey="beneform4j.core.util.tree.exist_repeated_node"/>
			<exception code="BF010308" description="根据代码获取节点失败" messageKey="beneform4j.core.util.tree.get_node_failure_by_code"/>
			<exception code="BF010309" description="节点索引超出范围" messageKey="beneform4j.core.util.tree.node_index_out_of_bounds"/>
		</exception>
	</exception>
</exception-config>
